[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["invest-sdr-usle-c-raster"]

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "invest-sdr-usle-c-raster"
version = "0.0.1"
dependencies = [
    "taskgraph @ git+https://github.com/natcap/taskgraph.git@main",
    "pygeoprocessing",
    "natcap.invest @ git+https://github.com/natcap/invest.git@feature/plugins"
]
requires-python = ">=3.9"
description = "Sediment Delivery Ratio (SDR) with USLE C raster (an InVEST plugin)"

[tool.natcap.invest]
api_version = "0.0.1"
model_id = "invest-sdr-usle-c-raster"  # model identifier used internally
model_title = "Sediment Delivery Ratio with USLE C Raster Input"  # user-facing name
pyname = "invest-sdr-usle-c-raster"
conda_dependencies = [ # to install into the plugin's conda env (not available thru pip)
  "gdal",
  "geotiff>=1.7.3"  # earlier versions don't support space in CONDA_PREFIX
]